# Generated by Django 3.2.7 on 2021-09-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slog',
            new_name='slug',
        ),
    ]
